import logo from './logo.svg';
import './App.css';
import SpendMoney from './component/SpendMoney';

function App() {

  const handleReset= () =>{
    window.location.reload();
  };
  return (

   <div>
    <h2> To Spend $128,000,000,000 You have money</h2>
   <div className='meme'>
   
   <SpendMoney
      id={"1"}
       image={
        "https://ayb.akinoncdn.com/products/2019/01/18/3544/5aa1ee14-1c83-4213-a62b-773c4785e187_size780x780_quality60_cropCenter.jpg"
      }
      name={"Coca"}
      price={"6"}
    />
   <SpendMoney
      id={"2"}
       image={
        "https://www.coca-cola.com.tr/content/dam/one/tr/tr/product-images/fanta-portakal_product_image.png"}
      name={"Coca"}
      price={"6"}
    />  
   <SpendMoney
      id={"3"}
       image={
        "https://images.ofix.com/product-image/s99509_2.jpg"
      }
      name={"Coca"}
      price={"6"}
    />
   <SpendMoney
      id={"4"}
       image={
        "https://konyamevlana.com/florya/wp-content/uploads/2020/12/sutas-ayran-285ml.jpg"
      }
      name={"Coca"}
      price={"6"}
    />
   <SpendMoney
      id={"5"}
       image={
        "http://esenlik.com.tr//images/prod/5704.jpg"
      }
      name={"Coca"}
      price={"6"}
    />
   <SpendMoney
      id={"6"}
       image={
        "https://evidea.akinoncdn.com/products/2021/08/05/62421/e5bda9ce-91bf-453a-96e1-acea983efb2a.jpg"
      }
      name={"Coca"}
      price={"6"}
    />
   <SpendMoney
      id={"7"}
       image={
        "https://media.istockphoto.com/photos/turkish-coffee-foamy-picture-id510413268?k=20&m=510413268&s=612x612&w=0&h=llBhDOUbNHaQXc-ch7UQ_OIWkmJAJUzaf6oZavKUrmQ="
      }
      name={"Coca"}
      price={"6"}
    />
   <SpendMoney
      id={"8"}
       image={
        "http://esenlik.com.tr//images/prod/2928.jpg"
      }
      name={"Coca"}
      price={"6"}
    />
   <SpendMoney
      id={"8"}
       image={
        "https://productimages.hepsiburada.net/s/37/375/10567819821106.jpg"
      }
      name={"Coca"}
      price={"6"}
    />
   <SpendMoney
      id={"8"}
       image={
        "https://www.dogansaatcilik.com.tr/ProductImages/118687/big/seiko-ssc719p-erkek-kol-saati__0296960735052182.jpg"
      }
      name={"Coca"}
      price={"6"}
    />
   <SpendMoney
      id={"8"}
       image={
        "https://productimages.hepsiburada.net/s/34/375/10460429320242.jpg"
      }
      name={"Coca"}
      price={"6"}
    />
   <SpendMoney
      id={"8"}
       image={
        "https://cdn.yemek.com/mnresize/940/940/uploads/2020/04/lahmacun-yeni-one-cikan.jpg"
      }
      name={"Coca"}
      price={"6"}
    />
   <SpendMoney
      id={"8"}
       image={
        "https://foto.haberler.com/haber/2020/12/07/israil-de-4-odali-malikane-250-milyon-dolarda-13784975_amp.jpg"
      }
      name={"Coca"}
      price={"6"}
    />
   <SpendMoney
      id={"8"}
       image={
        "https://image.elitema.com.tr/db_images/224/4/11/arimg1138-8---bell-429-exter%C4%B1or.jpg"
      }
      name={"Coca"}
      price={"6"}
    />
   <SpendMoney
      id={"8"}
       image={
        "https://d.neoldu.com/news/57966.jpg"
      }
      name={"Coca"}
      price={"6"}
    />
   <SpendMoney
      id={"8"}
       image={
        "https://img.paratic.com/dosya/2015/03/dunyanin-en-pahali-limuzinleri-1024x683.jpg"
      }
      name={"Coca"}
      price={"6"}
    />
   <SpendMoney
      id={"8"}
       image={
        "https://icdn.ensonhaber.com/resimler/galeri/1_11195.jpg"
      }
      name={"Coca"}
      price={"6"}
    />
   <SpendMoney
      id={"8"}
       image={
        "https://cdnuploads.aa.com.tr/uploads/Contents/2020/06/01/thumbs_b_c_dc24a18cc233bd960f410911f5d39bf2.jpg"
      }
      name={"Coca"}
      price={"6"}
    />
   <SpendMoney
      id={"8"}
       image={
        "https://www.cumhuriyet.com.tr/Archive/2021/9/27/1872247/kapak_141123.jpg"
      }
      name={"Coca"}
      price={"6"}
    />
   <SpendMoney
      id={"8"}
       image={
        "https://st2.myideasoft.com/idea/fr/55/myassets/products/366/paris-saint-germain-cup-away-stadium-shirt-2021-22-kids-with-messi-30-printing-ss4-p-12087703-u-6v44pc9ht2ynaiyuv5uk-v-af3dfad2f9b44448a3068821419095db_min.jpg?revision=1628627354"
      }
      name={"Coca"}
      price={"6"}
    />
 
   </div>
   <div className="endgame">
            <tr>
              <td><input></input></td>
            </tr>
             <tr><td><input></input></td></tr> 
            <tr>
              <td><input></input></td>
              <td><button className='abc' onClick={handleReset}>Reset</button></td>
            </tr>  
          </div>
  </div>
  );
}

export default App;
